version: "3.8"

services:
  frontend:
    build:
      context: ../..
      dockerfile: docker/production/frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}

  backend:
    build:
      context: ../..
      dockerfile: docker/production/backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${RTMP_INJECT_PORT}:${RTMP_INJECT_PORT}"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/${MONGODB_DB_NAME}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
      - RTMP_INJECT_PORT=${RTMP_INJECT_PORT}
      - RTMP_INJECT_PUBLIC_URL=${RTMP_INJECT_PUBLIC_URL}
      - RTMP_INJECT_LINK_ROOT=${RTMP_INJECT_LINK_ROOT}

  mongodb:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
