version: "3.8"

services:
  frontend:
    image: open-stream-hub-frontend:latest
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - REST_API_HOST=${REST_API_HOST}
      - REST_API_PORT=${REST_API_PORT}

  backend:
    image: open-stream-hub-backend:latest
    restart: always
    ports:
      - "${REST_API_PORT}:${REST_API_PORT}"
      - "${RTMP_INJECT_PORT}:${RTMP_INJECT_PORT}"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/${MONGODB_DB_NAME}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - REST_API_PORT=${REST_API_PORT}
      - RTMP_INJECT_PORT=${RTMP_INJECT_PORT}
      - RTMP_INJECT_PUBLIC_URL=${RTMP_INJECT_PUBLIC_URL}
      - RTMP_INJECT_LINK_ROOT=${RTMP_INJECT_LINK_ROOT}
      - RTMP_PLAY_SECRET=${RTMP_PLAY_SECRET}
      - REALTIME_THUMBNAIL_DISABLED=${REALTIME_THUMBNAIL_DISABLED}

  mongodb:
    image: mongo:latest
    restart: always
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
