version: "3.8"

services:
  frontend:
    image: open-stream-hub-frontend:latest
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_REST_API_HOST=http://localhost:6636

  backend:
    image: open-stream-hub-backend:latest
    restart: always
    ports:
      - "6636:6636"  # Rest API port
      - "1935:1935"  # RTMP RTMP server port
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/open-stream-hubV2
      - REST_API_PORT=6636
      - RTMP_SERVER_PORT=1935
      - RTMP_INJECT_HOST=rtmp://localhost
      - RTMP_INJECT_ROOT=/inject
      - RTMP_WATCH_ROOT=/watch
      - HSL_PREVIEW_ENABLED=true

  mongodb:
    image: mongo:latest
    restart: always
    # ports:
    #   - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
